default: &default
    adapter: 'sqlite3'
    database: './facturas.db'

development:
    <<: *default
    database: './facturas.db'

production:
    <<: *default
    database: './facturas.db'

test:
    <<: *default
    database: ":memory:"
